# language
language: swift
swift: 4.1

# xcode
os: osx
osx_image: xcode9.4
xcode_project: yaft-cocoa.xcodeproj
xcode_scheme: yaft-cocoa

# misc
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
env:
  global:
    - RELEASE_FILE="yaft-cocoa-nightly-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1).tar.gz"

# build
before_install:
  - gem install xcpretty
  - brew install jq
  - gem environment
before_script:
  - set -o pipefail
script:
  - xcodebuild -project yaft-cocoa.xcodeproj -scheme yaft-cocoa -destination 'platform=macOS,arch=x86_64' -sdk macosx10.13 | xcpretty -c

# automatically create merge pull-request
after_success:
  - ./.travis/create_merge_pr.sh

# deploy github releases
before_deploy:
  - tar cf ${RELEASE_FILE} build/Release/yaft-cocoa.app
deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: ${RELEASE_FILE}
  skip_cleanup: true
  on:
    tags: false
